# Generated by Django 4.2.6 on 2023-10-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_rename_decription_project_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-vote_ratio", "-vote_total", "title"]},
        ),
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
