# Generated by Django 4.2.6 on 2023-11-02 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_project_options_alter_review_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={},
        ),
    ]
