# Generated by Django 4.2.6 on 2023-11-07 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_rename_social_youtube_profile_social_stackoverflow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="username",
            new_name="membername",
        ),
    ]
