# Generated by Django 4.2.6 on 2023-11-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0004_rename_username_profile_membername"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="name",
        ),
        migrations.AddField(
            model_name="skill",
            name="membername",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
