# Generated by Django 4.2.6 on 2023-11-07 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_remove_skill_name_skill_membername"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skill",
            old_name="membername",
            new_name="name",
        ),
    ]
