# Generated by Django 4.2.6 on 2023-11-07 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0006_rename_membername_skill_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="membername",
            new_name="username",
        ),
    ]
